import Head from "next/head";

import { Button, Text } from "@mantine/core";
import { Workout } from "../components";
import { IconPlus } from "@tabler/icons";

export default function Home() {
  return (
    <div>
      <Head>
        <title>A workout app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <div className="flex">
        <h1>Good evening</h1>
        <img src="/favicon.ico" alt="my_logo" />
      </div>

      {/* Today's workout section */}
      <div>
        <h1>Today&apos;s workouts</h1>
        {[1, 2, 3, 4, 5, 6, 7].map((el) => (
          <Workout key={el} today />
        ))}
      </div>

      {/* Upcoming workouts */}
      <div>
        <h1>Upcoming workouts</h1>
        {[1, 2, 3, 4, 5, 6, 7].map((el) => (
          <Workout key={el} />
        ))}
      </div>

      {/* Stats */}
      <div>
        <h1>Stats</h1>
        Heatmap
      </div>

      {/* Add workout button */}
      <div>
        <Button>
          <IconPlus />
        </Button>
      </div>
    </div>
  );
}
